substance 'Continuity' active
   description        ''
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
parameter 'Salinity'
   description   'Salinity'
   unit          '(g/kg)'
   value          0.3500E+02
end-parameter
parameter 'PeriodVTRA'
   description   'period for calculating vertical distribution'
   unit          '(h)'
   value         24.
end-parameter
active-processes
   name  'Salinchlor' 'Conversion of salinity into chloride or vv'
   name  'VertDisp' 'Vertical dispersion (segment -> exchange)'
   name  'DynDepth' 'dynamic calculation of the depth'
   name  'vtrans' 'Vertical mixing distribution over a period'
   name  'TotDepth' 'depth water column'
end-active-processes
