substance 'Continuity' active
   description        'Continuity'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'cTR1' active
   description        'Conservative Tracer Source 1'
   concentration-unit '(g/m3)'
   waste-load-unit    '-'
end-substance
substance 'Salinity' active
   description        'Salinity'
   concentration-unit '(g/kg)'
   waste-load-unit    '-'
end-substance
active-processes
end-active-processes